document.addEventListener('DOMContentLoaded', () => {
  addAddition()
  addSubtraction()
  addMultiplication()
  addDivision()
  setupInitialStore()
  clearLastCalculation()
  clearAllCalculation()
	console.log('DOM loaded')
})
